Re-add the trixie upgrade support code, needed from Noble.
Can be removed in the 26.10 cycle.

Revert "debian/debhelper.in/libc.postinst: remove support code to upgrade to trixie."

This reverts commit 2052fc4a3f3e98d71bf1aea74d2b0d5554d355fd.

Also contains this fix from Helmut:

libc.postinst: Don't restart systemd when it does not work

This restores the earlier behavior and matches what the comment says.

Fixes: 92b8b2dbd3aa ("Partially restore init restarting. (Closes: #1108193)")

diff --git a/debian/debhelper.in/libc.postinst b/debian/debhelper.in/libc.postinst
--- a/debian/debhelper.in/libc.postinst
+++ b/debian/debhelper.in/libc.postinst
@@ -118,6 +118,30 @@ then
 	fi
     fi # Upgrading
 
+# begin-remove-after: released:26.04
+    # Restart systemd. Starting with trixie, inits restart themselves via
+    # dpkg-triggers. For inits other than systemd, versioned Breaks have been
+    # declared, but doing so for systemd would create a cycle.
+    if ! command -v systemd >/dev/null; then
+	: # The systemd binary has been moved out of $PATH in trixie.
+	# systemd's trigger interest or its postinst will handle reexecuting.
+    elif [ -n "${DPKG_ROOT:-}" ] || ischroot 2>/dev/null; then
+	: # Do not re-exec init if we are operating on a chroot.
+    elif [ -d /run/systemd/system ]; then
+	# Restart systemd on upgrade, but carefully.
+	# The restart is wanted because of LP: #1942276 and Bug: #993821
+	# The care is needed because of https://bugs.debian.org/753725
+	# (if systemd --help fails the system might still be quite broken but
+	# that seems better than the kernel panic that results if systemd
+	# cannot reexec itself).
+	if systemd --help >/dev/null 2>/dev/null; then
+	    systemctl daemon-reexec
+	else
+	    echo "Error: Could not restart systemd, systemd binary not working" >&2
+	fi
+    fi
+
+# end-remove-after
     # Emit triggers to allow depending packages to restart themselves if
     # needed.  The triggers are called with "--no-await", as packages with the
     # triggers-awaited state do not satisfy dependencies.
