2.44-1ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/debhelper.in/libc.postinst b/debian/debhelper.in/libc.postinst
--- a/debian/debhelper.in/libc.postinst
+++ b/debian/debhelper.in/libc.postinst
@@ -26,127 +26,122 @@ then
 
     if [ -n "$preversion" ] && [ -x "$(command -v ischroot)" ] && ! ischroot; then
 	if dpkg --compare-versions "$preversion" lt DEB_VERSION_UPSTREAM; then
-	    check="apache2.2-common apache apache-ssl apache-perl autofs at"
-	    check="$check boa cucipop courier-authdaemon cron cups exim"
-	    check="$check exim4-base dovecot-common cucipop incron lprng lpr"
-	    check="$check lpr-ppd mysql-server nis openbsd-inetd"
-	    check="$check openldapd openssh-server postgresql-common proftpd"
-	    check="$check postfix postfix-tls rsync samba sasl2-bin slapd"
-	    check="$check smail sendmail snmpd spamassassin vsftpd"
-	    check="$check wu-ftpd wu-ftpd-academ wwwoffle"
-	    check="$check webmin dropbear gdm"
-	    # NSS services check: 
-	    __NSS_CHECK__
-	    if [ -n "$services" ]; then
+	    check=""
+	    [ -f /var/run/services.need_restart ] && check=$(sort -u /var/run/services.need_restart 2>/dev/null)
+	    # Change service names back into package names, so that we can
+	    # double-check package installation.
+	    check=$(echo "$check" | \
+                    sed -e's/\batd\b/at/g' \
+                        -e's/\bdovecot\b/dovecot-common/g' \
+                        -e's/\bexim4\b/exim4-base/g' \
+                        -e's/\blpd\b/lpr/g' \
+                        -e's/\blpd-ppd\b/lpr-ppd/g' \
+                        -e's/\bmysql\b/mysql-server/g' \
+                        -e's/\bsaslauthd\b/sasl2-bin/g' \
+                        -e's/\bsmbd\b/samba/g' \
+                        -e's/\bpostgresql\b/postgresql-common/g' \
+                    )
 
-	        if [ -f /usr/share/debconf/confmodule ] ; then
-		    db_version 2.0
-		    db_input critical libraries/restart-without-asking || true
-		    db_go || true
-		    db_get libraries/restart-without-asking
-		    if [ "$RET" != true ]; then
-			db_reset glibc/restart-services
-			db_set glibc/restart-services "$services"
-			db_input critical glibc/restart-services || true
-			db_go || true
-			db_get glibc/restart-services
-			if [ "x$RET" != "x" ]
-			then
-			    services="$RET"
+	    # Check to see which of the services that were running at unpack
+	    # time are still around
+            # the following substitution processes the check variable
+            # and returns results in the services variable
+	    # NSS services check:
+	    __NSS_CHECK__
+	    # If there are services that we *stopped* in the preinst, don't
+	    # forget to restart them now
+	    if [ -e /var/run/services.need_start ]; then
+		services="$(sort -u /var/run/services.need_start) $services"
+	    fi
+	    if [ -n "$services" ]; then
+		echo "Restarting services possibly affected by the upgrade:"
+		failed=""
+		for service in $services; do
+		    case "$service" in
+			gdm*)
+			    idlopt="reload"
+			    ;;
+			*)
+			    idlopt="restart"
+			    ;;
+		    esac
+		    echo -n "  $service: restarting..."
+		    if invoke-rc.d ${service} $idlopt > /dev/null 2>&1; then
+			echo "done."
+		    else
+			echo "FAILED! ($?)"
+			failed="$service $failed"
+		    fi
+		done
+	
+		echo
+		if [ -n "$failed" ]; then
+		    if [ -f /usr/share/debconf/confmodule ] ; then
+			db_fset glibc/restart-failed seen false
+			db_subst glibc/restart-failed services "$failed"
+			if [ "$RELEASE_UPGRADE_MODE" = desktop ]; then
+			    db_input medium glibc/restart-failed || true
 			else
-			    services=""
+			    db_input critical glibc/restart-failed || true
+			fi
+			db_go || true
+		    else
+			echo "The following services failed to start: $failed"
+			echo
+			echo "You will need to start these manually by running \`invoke-rc.d <service> start'"
+			echo "If the service still fails to start, you may need to file a bug on"
+			echo "${DPKG_MAINTSCRIPT_PACKAGE}:${DPKG_MAINTSCRIPT_ARCH} or the service involved."
+			frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
+			if [ "$frontend" != noninteractive ]; then
+			    echo
+			    echo -n "Press ENTER to continue: "
+			    read foo
 			fi
 		    fi
 		else
-		    echo
-		    echo "Name Service Switch update in the C Library: post-installation question."
-		    echo
-		    echo "Running services and programs that are using NSS need to be restarted,"
-		    echo "otherwise they might not be able to do lookup or authentication any more"
-		    echo "(for services such as ssh, this can affect your ability to login)."
-		    echo "Note: restarting sshd/telnetd should not affect any existing connections."
-		    echo
-		    echo "The services detected are: "
-		    echo "        $services"
-		    echo
-		    echo "If other services have begun to fail mysteriously after this upgrade, it is"
-		    echo "probably necessary to restart them too.  We recommend that you reboot your"
-		    echo "machine after the upgrade to avoid NSS-related troubles."
-		    echo
-		    frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
-		    if [ "$frontend" = noninteractive ]; then
-		    	echo "Non-interactive mode, restarting services"
-		    	answer=yes
-		    else
-		    	echo -n "Do you wish to restart services? [Y/n] "
-		    	read answer
-		    	case $answer in
-			    N*|n*) services="" ;;
-			    *) ;;
-		        esac
-		    fi
+		    echo "Services restarted successfully."
+		    rm -f /var/run/services.need_start /var/run/services.need_restart
 		fi
-		echo
-		if [ "$services" != "" ]; then
-		    echo "Restarting services possibly affected by the upgrade:"
-		    failed=""
-		    for service in $services; do
-			case "$service" in
-			    gdm)
-				echo -n "  $service: reloading..."
-				if invoke-rc.d ${service} reload > /dev/null 2>&1; then
-				    echo "done."
-				else
-				    echo "FAILED! ($?)"
-				    failed="$service $failed"
-				fi
-				;;
-			    *)
-				echo -n "  $service: restarting..."
-				if invoke-rc.d ${service} restart > /dev/null 2>&1; then
-				    echo "done."
-				else
-				    echo "FAILED! ($?)"
-				    failed="$service $failed"
-				fi
-				;;
-			esac
-		    done
-		    echo
-		    if [ -n "$failed" ]; then
-	        	if [ -f /usr/share/debconf/confmodule ] ; then
-		    	    db_fset glibc/restart-failed seen false
-			    db_subst glibc/restart-failed services "$failed"
-			    db_input critical glibc/restart-failed || true
-			    db_go || true
-			else
-			    echo "The following services failed to start: $failed"
-			    echo
-			    echo "You will need to start these manually by running \`invoke-rc.d <service> start'"
-			    echo "If the service still fails to start, you may need to file a bug on"
-			    echo "${DPKG_MAINTSCRIPT_PACKAGE}:${DPKG_MAINTSCRIPT_ARCH} or the service involved."
-			    frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
-			    if [ "$frontend" != noninteractive ]; then
-			    	echo
-			    	echo -n "Press ENTER to continue: "
-			    	read foo
-			    fi
-			fi
-		    else
-			echo "Services restarted successfully."
-                    fi
-		fi
-                # Shut down the frontend, to make sure none of the
+	
+		# Shut down the frontend, to make sure none of the
 		# restarted services keep a connection open to it
-	        if [ -f /usr/share/debconf/confmodule ] ; then
+		if [ -f /usr/share/debconf/confmodule ] ; then
 		    db_stop
 		fi
 	    else
 		echo "Nothing to restart."
 	    fi
 	fi # end upgrading and $preversion lt DEB_VERSION_UPSTREAM
+	# give a reboot notification on al upgrades (LP: #1546457)
+	if [ -x /usr/share/update-notifier/notify-reboot-required ]; then
+	    /usr/share/update-notifier/notify-reboot-required
+	fi
     fi # Upgrading
 
+# begin-remove-after: released:26.04
+    # Restart systemd. Starting with trixie, inits restart themselves via
+    # dpkg-triggers. For inits other than systemd, versioned Breaks have been
+    # declared, but doing so for systemd would create a cycle.
+    if ! command -v systemd >/dev/null; then
+	: # The systemd binary has been moved out of $PATH in trixie.
+	# systemd's trigger interest or its postinst will handle reexecuting.
+    elif [ -n "${DPKG_ROOT:-}" ] || ischroot 2>/dev/null; then
+	: # Do not re-exec init if we are operating on a chroot.
+    elif [ -d /run/systemd/system ]; then
+	# Restart systemd on upgrade, but carefully.
+	# The restart is wanted because of LP: #1942276 and Bug: #993821
+	# The care is needed because of https://bugs.debian.org/753725
+	# (if systemd --help fails the system might still be quite broken but
+	# that seems better than the kernel panic that results if systemd
+	# cannot reexec itself).
+	if systemd --help >/dev/null 2>/dev/null; then
+	    systemctl daemon-reexec
+	else
+	    echo "Error: Could not restart systemd, systemd binary not working" >&2
+	fi
+    fi
+
+# end-remove-after
     # Emit triggers to allow depending packages to restart themselves if
     # needed.  The triggers are called with "--no-await", as packages with the
     # triggers-awaited state do not satisfy dependencies.
diff --git a/debian/local/usr_sbin/locale-gen b/debian/local/usr_sbin/locale-gen
--- a/debian/local/usr_sbin/locale-gen
+++ b/debian/local/usr_sbin/locale-gen
@@ -1,18 +1,91 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 
 LOCALEGEN=/etc/locale.gen
 LOCALES=/usr/share/i18n/locales
 USER_LOCALES=/usr/local/share/i18n/locales
+SUPPORTED=/var/lib/locales/supported.d
 
 
 [ -s "$LOCALEGEN" ] || exit 0
 
-[ "$1" = '--keep-existing' ] && KEEP=1 || KEEP=0
+KEEP=0
+IS_LANG=no
+ARCHIVE=yes
 
-# Remove old locale-archive before generating new locale data
-[ "$KEEP" -eq 0 ] && rm -rf /usr/lib/locale/locale-archive || :
+#  Handle command-line options
+prev=
+while true
+do
+	option="$1"
+	if [ -n "$prev" ]; then
+                eval "$prev=\$option"
+                prev=
+                continue
+	fi
+
+	case $option in
+	-h|--help)
+		cat <<EOT
+Usage: locale-gen [OPTIONS]
+Options:
+ -h, --help         display this message and exit
+     --purge        remove existing locales before processing
+     --archive      store compiled locale data inside a single archive
+     --no-archive   do not store compiled locale data inside a single archive
+                    (default)
+     --lang         treat argument as generic language code
+EOT
+		exit 0
+		;;
+	--purge)
+		# This is the default when called without arguments
+		;;
+	--no-purge)
+		KEEP=1
+		;;
+	--archive)
+		ARCHIVE=yes
+		;;
+	--no-archive)
+		ARCHIVE=no
+		;;
+	--keep-existing)
+		KEEP=1
+		;;
+	--lang)
+		IS_LANG=yes
+		;;
+	--*)
+		echo "locale-gen: invalid option -- $option"
+		echo "Try 'locale-gen --help' for more information."
+		exit 1
+		;;
+	*)
+		break
+		;;
+	esac
+
+	shift
+done
+
+no_archive=
+[ "$ARCHIVE" = yes ] || no_archive="--no-archive"
+
+if [ -z "$1" ] && [ "$KEEP" -eq 0 ]; then
+	# Remove all old locale dir and locale-archive before generating new
+	# locale data.
+	rm -rf /usr/lib/locale/locale-archive || true
+	for dir in /usr/lib/locale/*; do
+		[ -e "$dir" ] || continue
+		if [ "${dir#/usr/lib/locale/}" = C.utf8 ]; then
+			# owned by libc-bin
+			continue
+		fi
+		rm -rf "$dir" 2>/dev/null || true
+	done
+fi
 
 umask 022
 
@@ -29,8 +102,46 @@ if [ -z "${I18NPATH:-}" ]; then
   fi
 fi
 
+add_to_locale_gen() {
+  echo "$1" | while read locale; do
+    if ! grep -q "^[# ]*$locale *\$" $LOCALEGEN; then
+      echo "# $locale" >> $LOCALEGEN
+    fi
+    sed -i -e "0,/^[# ]*$locale *$/ s/^[# ]*$locale *$/$locale/" $LOCALEGEN
+  done
+}
+
+if [ -z "$1" ]; then
+  GENERATE="`cat $SUPPORTED/* $LOCALEGEN 2>/dev/null || true`"
+else
+  GENERATE=
+  while [ -n "$1" ]; do
+    if [ -f "$SUPPORTED/$1" ]; then
+      GENERATE="$GENERATE\n`cat $SUPPORTED/$1`"
+    elif [ $IS_LANG = no ] && L=`grep "^${1/%.utf8/.UTF-8} " /usr/share/i18n/SUPPORTED`; then
+      # convert utf8 to UTF-8 and check if the requested locale exists
+      GENERATE="$GENERATE\n$L"
+      add_to_locale_gen "$L"
+    elif [ $IS_LANG = no ] && L=`grep "^${1%.[uU][tT][fF]*} UTF-8" /usr/share/i18n/SUPPORTED`; then
+      # recognize 'll_CC.UTF-8' or 'll_CC.utf8' as ll_CC without codeset
+      GENERATE="$GENERATE\n$L"
+      add_to_locale_gen "$L"
+    else
+      # try to come up with a sensible default
+      L=`grep -E "^${1}( |[._@][^[:space:]]* )UTF-8" /usr/share/i18n/SUPPORTED || true`
+      if [ -z "$L" ]; then
+        echo "Error: '$1' is not a supported language or locale" >&2
+        exit 1
+      fi
+      GENERATE="$GENERATE\n$L"
+      add_to_locale_gen "$L"
+    fi
+    shift
+  done
+fi
+
 echo "Generating locales (this might take a while)..."
-while read -r locale charset; do
+echo -e "$GENERATE" | sort -u | while read -r locale charset; do \
 	if [ -z "$locale" ] || [ "${locale#\#}" != "$locale" ]; then continue; fi
 	is_entry_ok || continue
 
@@ -52,7 +163,7 @@ while read -r locale charset; do
 			input="$USER_LOCALES/$input"
 		fi
 	fi
-	I18NPATH="${I18NPATH}" localedef -i "$input" -c -f "$charset" "$locale" || :
+	I18NPATH="${I18NPATH}" localedef $no_archive -i $input -c -f $charset $locale || :
 	echo " done"
-done < "$LOCALEGEN"
+done
 echo "Generation complete."
