2.42-0ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/debhelper.in/libc.preinst b/debian/debhelper.in/libc.preinst
--- a/debian/debhelper.in/libc.preinst
+++ b/debian/debhelper.in/libc.preinst
@@ -107,31 +107,6 @@ then
             fi
         fi
 
-    elif [ $system = "GNU/kFreeBSD" ]
-    then
-        kernel_ver=`uname -r`
-        kernel_ver_min=8.3
-        if kernel_compare_versions "$kernel_ver" lt $kernel_ver_min
-        then
-            if [ "$USE_DEBCONF" ]
-            then
-                db_version 2.0
-                db_version 2.0
-                db_fset glibc/kernel-too-old seen false
-                db_reset glibc/kernel-too-old
-                db_subst glibc/kernel-too-old kernel_ver $kernel_ver_min
-                db_input critical glibc/kernel-too-old || true
-                db_go
-                db_stop
-            else
-                echo "ERROR: This version of the GNU libc requires kernel version"
-                echo "$kernel_ver_min or later.  Please upgrade your kernel and reboot before installing"
-                echo 'glibc. You may need to use "apt -f install" after reboot to solve dependencies.'
-                echo
-            fi
-            exit 1
-        fi
-
     elif [ $system = "GNU" ]
     then
         kernel_ver=`uname -v | cut -d / -f 1 | cut -d ' ' -f 2`
@@ -205,7 +180,11 @@ then
 	            db_version 2.0
 		    db_reset glibc/upgrade
 		    db_subst glibc/upgrade services $services
-		    db_input critical glibc/upgrade || true
+		    if [ "$RELEASE_UPGRADE_MODE" = desktop ]; then
+			db_input medium glibc/upgrade || true
+		    else
+			db_input critical glibc/upgrade || true
+		    fi
 		    db_go || true
 		    db_get glibc/upgrade
 		    answer=$RET
@@ -249,32 +228,101 @@ then
 		fi
 	    fi
 
-            # As long systemd-logind has not seen any login request since the system has been
-            # booted, it has not loaded any NSS module. In that condition if glibc is upgraded
-            # (that means with a non session shell or by some automation), the NSS modules are
-            # replaced by a new major version which might be incompatible (and definitely are
-            # for some versions).
-            #
-            # The solution implemented for most daemons is to restart them, but unfortunately
-            # it is not something supported with systemd-logind (see bug#91950).
-            #
-            # As a workaround, when detected that the system is using systemd and that the
-            # systemd-logind process has not not loaded any NSS module, force systemd-logind to
-            # load NSS modules. This is done by disabling lingering on a non-existing user. This
-            # has to be done by talking directly to systemd-logind through sd-bus, as loginctl
-            # first checks if the user actually exist. The nonexistent uid is chosen as
-            # 4294967294, which is reserved by Policy §9.2.2.
-            #
-            # Note that starting with glibc 2.34, the nss_files is builtin. When glibc >= 2.34
-            # ends-up in a stable release, this workaround can therefore be dropped.
-            if dpkg --compare-versions "$preversion" lt 2.34 && [ -d /run/systemd/system ]; then
-                if ! grep -q -E 'libnss_(compat|db|files)' /proc/$(systemctl show --property MainPID --value systemd-logind.service)/maps >/dev/null 2>&1; then
-                    echo "Forcing systemd-logind to load NSS modules..."
-                    busctl call --system org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager \
-                        SetUserLinger ubb 4294967294 false false >/dev/null 2>&1 || true
-                fi
-            fi
+	    services=""
+	    check="apache2 apache apache-ssl apache-perl autofs at"
+	    check="$check boa cucipop courier-authdaemon cron cups exim"
+	    check="$check exim4-base dovecot-common cucipop incron lprng lpr"
+	    check="$check lpr-ppd mysql-server nis openbsd-inetd"
+	    check="$check openldapd postgresql-common proftpd postfix postfix-tls"
+	    check="$check rsync samba sasl2-bin slapd smail sendmail snmpd ssh"
+	    check="$check spamassassin vsftpd wu-ftpd wu-ftpd-academ wwwoffle"
+	    check="$check webmin dropbear gdm gdm3"
+	    # the following substitution processes the check variable
+	    # and returns results in the services variable
+	    # NSS services check:
+	    __NSS_CHECK__
+	    if [ -n "$services" ] && [ ! -x /usr/lib/needrestart/apt-pinvoke ]; then
+	        if [ "$USE_DEBCONF" ] ; then
+	            db_version 2.0
+	            if [ "$RELEASE_UPGRADE_MODE" = desktop ]; then
+	                db_input medium libraries/restart-without-asking || true
+	            else
+	                db_input critical libraries/restart-without-asking || true
+	            fi
+	            db_go || true
+    
+	            db_get libraries/restart-without-asking
+	            if [ "$RET" != true ]; then
+	                db_reset glibc/restart-services
+	                db_set glibc/restart-services "$services"
+	                if [ "$RELEASE_UPGRADE_MODE" = desktop ]; then
+	                    db_input medium glibc/restart-services || true
+	                else
+	                    db_input critical glibc/restart-services || true
+	                fi
+	                db_go || true
+	                db_get glibc/restart-services
+	                services="$RET"
+	            fi
+	        else
+	            echo
+	            echo "Name Service Switch update in the C Library: post-installation question."
+	            echo
+	            echo "Running services and programs that are using NSS need to be restarted,"
+	            echo "otherwise they might not be able to do lookup or authentication any more"
+	            echo "(for services such as ssh, this can affect your ability to login)."
+	            echo "Note: restarting sshd/telnetd should not affect any existing connections."
+	            echo
+	            echo "The services detected are: "
+	            echo "        $services"
+	            echo
+	            echo "If other services have begun to fail mysteriously after this upgrade, it is"
+	            echo "probably necessary to restart them too.  We recommend that you reboot your"
+	            echo "machine after the upgrade to avoid NSS-related troubles."
+	            echo
+	            frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
+	            if [ "$frontend" = noninteractive ]; then
+	                    echo "Non-interactive mode, restarting services"
+	                    answer=yes
+	            else
+	                    echo -n "Do you wish to restart services? [Y/n] "
+	                    read answer
+	                    case $answer in
+	                    N*|n*) services="" ;;
+	                    *) ;;
+	                    esac
+	            fi
+	        fi
 
+	        if [ -n "$services" ]; then
+	            echo "Stopping some services possibly affected by the upgrade (will be restarted later):"
+	            for service in $services; do
+	                case "$service" in
+	                    cron)
+	                        # See bug (LP: #508083)
+	                        echo -n "  $service: stopping..."
+	                        if invoke-rc.d ${service} stop > /dev/null 2>&1; then
+	                            echo "done."
+	                            echo "$service" >> /var/run/services.need_start
+	                        else
+	                            echo "FAILED! ($?)"
+	                            echo "$service" >> /var/run/services.need_restart
+	                        fi
+	                      ;;
+
+	                    *)
+	                        # log service details to allow postinst to handle the
+	                        # restart.
+	                        echo "$service" >> /var/run/services.need_restart
+	                      ;;
+	                esac
+	            done
+    
+	        fi
+	        echo
+	    else
+	        echo "Nothing to restart."
+	    fi
 	fi # end upgrading and $preversion lt DEB_VERSION_UPSTREAM
     fi # Upgrading
 fi
@@ -314,6 +362,14 @@ if [ "$1" = install -o "$1" = upgrade ] && [ "$rtlddir" != "/lib" ]; then
         echo "Refusing to unpack. Please install the usrmerge package and try again."
         echo
         exit 1
+    fi
+    # Remove legacy 24.04 protective diversions without leading dot
+    # FIXME: Remove this after 26.04
+    if [ "$(dpkg-divert --truename $rtlddir)" = "$rtlddir.usr-is-merged" ]; then
+        dpkg-divert --quiet --package base-files --remove --no-rename --divert $rtlddir.usr-is-merged $rtlddir
+        if [ -d $rtlddir.usr-is-merged ]; then
+            mv --no-target-directory $rtlddir.usr-is-merged /.${rtlddir#/}.usr-is-merged
+        fi
     fi
     if dpkg --compare-versions "$(dpkg-query -f '${Version}' -W base-files)" le 13 || ! dpkg-query -L base-files | grep -qxF "$rtlddir"; then
         dpkg-divert --quiet --add --no-rename --package base-files --divert "/.${rtlddir#/}.usr-is-merged" "$rtlddir"
